
services:
  web:
    build: .
    container_name: xclone-web
    command: gunicorn -w 4 -b 0.0.0.0:8000 'app:create_app("config.ProductionConfig")'
    env_file: .env.prod 
    depends_on:
      - db
    restart: always
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: xclone-db
    restart: always
    env_file: .env.prod 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: xclone-nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do
      certbot renew;
      sleep 12h & wait $${!};
      done;"

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
