"""Change length of name and email

Revision ID: 309b21755901
Revises: ef072c7fc1c0
Create Date: 2025-08-29 07:17:52.834830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309b21755901'
down_revision = 'ef072c7fc1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
