"""remember token to remember digest

Revision ID: 82227ed8ba15
Revises: cdfaa08a7249
Create Date: 2025-09-22 14:18:43.605178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82227ed8ba15'
down_revision = 'cdfaa08a7249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_digest', sa.String(), nullable=True))
        batch_op.drop_column('remember_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_token', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('remember_digest')

    # ### end Alembic commands ###
