"""update size of password digest

Revision ID: 96af2d3d20de
Revises: 8e575a8172dc
Create Date: 2025-08-29 15:08:45.371646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96af2d3d20de'
down_revision = '8e575a8172dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_digest',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_digest',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
