"""initial

Revision ID: cdfaa08a7249
Revises: 
Create Date: 2025-09-13 17:25:27.309658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfaa08a7249'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_digest', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated_at')
        batch_op.drop_column('activated')
        batch_op.drop_column('activation_digest')

    # ### end Alembic commands ###
