"""add reset

Revision ID: db2fb0e4bba5
Revises: 82227ed8ba15
Create Date: 2025-09-26 15:57:50.178731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2fb0e4bba5'
down_revision = '82227ed8ba15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_digest', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_activation_digest'), ['activation_digest'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reset_digest'), ['reset_digest'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_digest'))
        batch_op.drop_index(batch_op.f('ix_users_activation_digest'))
        batch_op.drop_column('reset_sent_at')
        batch_op.drop_column('reset_digest')

    # ### end Alembic commands ###
